// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetInstanceId } from "./AssetInstanceId";
import type { SlotAssignment } from "./SlotAssignment";
import type { TemplateId } from "./TemplateId";

export type AssetInstance = { id: AssetInstanceId, name: string, templateId: TemplateId, slots: { [key in string]: SlotAssignment }, version: number, };
