// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartId } from "./PartId";
import type { SlotTag } from "./SlotTag";
import type { TextureSlot } from "./TextureSlot";
import type { Transform } from "./Transform";

export type Part = { id: PartId, name: string, tags: Array<SlotTag>, meshFile: string, defaultOffset: Transform, textureSlots: Array<TextureSlot>, thumbnailFile: string | null, };
