// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartId } from "./PartId";
import type { TextureId } from "./TextureId";
import type { Transform } from "./Transform";

export type SlotAssignment = { partId: PartId, offset: Transform, textures: { [key in string]?: TextureId }, };
