// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PartId } from "./PartId";
import type { SlotTag } from "./SlotTag";
import type { Transform } from "./Transform";

export type SlotDefinition = { tag: SlotTag, name: string, anchor: Transform, defaultPartId: PartId | null, pairedSlot: SlotTag | null, required: boolean, };
