// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlotDefinition } from "./SlotDefinition";
import type { TemplateId } from "./TemplateId";

export type Template = { id: TemplateId, name: string, description: string, slots: Array<SlotDefinition>, version: number, };
