// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextureId } from "./TextureId";

export type Texture = { id: TextureId, name: string, file: string, width: number, height: number, tags: Array<string>, };
