// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextureChannel } from "./TextureChannel";
import type { TextureId } from "./TextureId";

export type TextureSlot = { channel: TextureChannel, defaultTextureId: TextureId | null, };
